from __future__ import annotations
import numpy as np

# SMPL-H Mean Hand Pose Constants (from ComfyUI-HyMotion/body_model.py)
LEFT_HAND_MEAN_AA = np.array(
    [
        0.1117,
        0.0429,
        -0.4164,
        0.1088,
        -0.0660,
        -0.7562,
        -0.0964,
        -0.0909,
        -0.1885,
        -0.1181,
        0.0509,
        -0.5296,
        -0.1437,
        0.0552,
        -0.7049,
        -0.0192,
        -0.0923,
        -0.3379,
        -0.4570,
        -0.1963,
        -0.6255,
        -0.2147,
        -0.0660,
        -0.5069,
        -0.3697,
        -0.0603,
        -0.0795,
        -0.1419,
        -0.0859,
        -0.6355,
        -0.3033,
        -0.0579,
        -0.6314,
        -0.1761,
        -0.1321,
        -0.3734,
        0.8510,
        0.2769,
        -0.0915,
        -0.4998,
        0.0266,
        0.0529,
        0.5356,
        0.0460,
        -0.2774,
    ]
)
RIGHT_HAND_MEAN_AA = np.array(
    [
        0.1117,
        -0.0429,
        0.4164,
        0.1088,
        0.0660,
        0.7562,
        -0.0964,
        0.0909,
        0.1885,
        -0.1181,
        -0.0509,
        0.5296,
        -0.1437,
        -0.0552,
        0.7049,
        -0.0192,
        0.0923,
        0.3379,
        -0.4570,
        0.1963,
        0.6255,
        -0.2147,
        0.0660,
        0.5069,
        -0.3697,
        0.0603,
        0.0795,
        -0.1419,
        0.0859,
        0.6355,
        -0.3033,
        0.0579,
        0.6314,
        -0.1761,
        0.1321,
        0.3734,
        0.8510,
        -0.2769,
        0.0915,
        -0.4998,
        -0.0266,
        -0.0529,
        0.5356,
        -0.0460,
        0.2774,
    ]
)

# =============================================================================
# Retargeting Configuration & Presets
# =============================================================================

BASE_BONE_MAPPING = {
    "hips": "mixamorig:hips",
    "pelvis": "mixamorig:hips",
    "spine": "mixamorig:spine",
    "spine1": "mixamorig:spine",
    "spine2": "mixamorig:spine1",
    "spine3": "mixamorig:spine2",
    "chest": "mixamorig:spine2",
    "neck": "mixamorig:neck",
    "neck1": "mixamorig:neck",
    "neck2": "mixamorig:neck",
    "head": "mixamorig:head",
    "head1": "mixamorig:head",
    "leftupleg": "mixamorig:leftupleg",
    "rightupleg": "mixamorig:rightupleg",
    "leftleg": "mixamorig:leftleg",
    "rightleg": "mixamorig:rightleg",
    "leftfoot": "mixamorig:leftfoot",
    "rightfoot": "mixamorig:rightfoot",
    "leftshoulder": "mixamorig:leftshoulder",
    "rightshoulder": "mixamorig:rightshoulder",
    "leftarm": "mixamorig:leftarm",
    "rightarm": "mixamorig:rightarm",
    "leftforearm": "mixamorig:leftforearm",
    "rightforearm": "mixamorig:rightforearm",
    "lefthand": "mixamorig:lefthand",
    "righthand": "mixamorig:righthand",
    # SMPL-H Naming Style (Explicit)
    "l_collar": "mixamorig:leftshoulder",
    "r_collar": "mixamorig:rightshoulder",
    "l_shoulder": "mixamorig:leftarm",
    "r_shoulder": "mixamorig:rightarm",
    "l_elbow": "mixamorig:leftforearm",
    "r_elbow": "mixamorig:rightforearm",
    "l_wrist": "mixamorig:lefthand",
    "r_wrist": "mixamorig:righthand",
    # SMPL-H Uppercase variants (CRITICAL for proper matching)
    "L_Wrist": "mixamorig:lefthand",
    "R_Wrist": "mixamorig:righthand",
    "L_Elbow": "mixamorig:leftforearm",
    "R_Elbow": "mixamorig:rightforearm",
    "L_Shoulder": "mixamorig:leftarm",
    "R_Shoulder": "mixamorig:rightarm",
    "L_Collar": "mixamorig:leftshoulder",
    "R_Collar": "mixamorig:rightshoulder",
    # Explicit SMPL-H and Common Hand variations
    "left_hand": "mixamorig:lefthand",
    "right_hand": "mixamorig:righthand",
    "left_wrist": "mixamorig:lefthand",
    "right_wrist": "mixamorig:righthand",
    "lhand": "mixamorig:lefthand",
    "rhand": "mixamorig:righthand",
    # Fingers - Left Hand
    "leftthumb1": "mixamorig:lefthandthumb1",
    "leftthumbmedial": "mixamorig:lefthandthumb1",
    "leftthumb2": "mixamorig:lefthandthumb2",
    "leftthumbdistal": "mixamorig:lefthandthumb2",
    "leftthumb3": "mixamorig:lefthandthumb3",
    "l_thumb1": "mixamorig:lefthandthumb1",
    "l_thumb2": "mixamorig:lefthandthumb2",
    "l_thumb3": "mixamorig:lefthandthumb3",
    "leftindex1": "mixamorig:lefthandindex1",
    "leftindexmedial": "mixamorig:lefthandindex1",
    "leftindex2": "mixamorig:lefthandindex2",
    "leftindexdistal": "mixamorig:lefthandindex2",
    "leftindex3": "mixamorig:lefthandindex3",
    "l_index1": "mixamorig:lefthandindex1",
    "l_index2": "mixamorig:lefthandindex2",
    "l_index3": "mixamorig:lefthandindex3",
    "leftmiddle1": "mixamorig:lefthandmiddle1",
    "leftmiddle2": "mixamorig:lefthandmiddle2",
    "leftmiddle3": "mixamorig:lefthandmiddle3",
    "l_middle1": "mixamorig:lefthandmiddle1",
    "l_middle2": "mixamorig:lefthandmiddle2",
    "l_middle3": "mixamorig:lefthandmiddle3",
    "leftring1": "mixamorig:lefthandring1",
    "leftringmedial": "mixamorig:lefthandring1",
    "leftring2": "mixamorig:lefthandring2",
    "leftringdistal": "mixamorig:lefthandring2",
    "leftring3": "mixamorig:lefthandring3",
    "l_ring1": "mixamorig:lefthandring1",
    "l_ring2": "mixamorig:lefthandring2",
    "l_ring3": "mixamorig:lefthandring3",
    "leftpinky1": "mixamorig:lefthandpinky1",
    "leftlittlemedial": "mixamorig:lefthandpinky1",
    "leftpinky2": "mixamorig:lefthandpinky2",
    "leftlittledistal": "mixamorig:lefthandpinky2",
    "leftpinky3": "mixamorig:lefthandpinky3",
    "l_pinky1": "mixamorig:lefthandpinky1",
    "l_pinky2": "mixamorig:lefthandpinky2",
    "l_pinky3": "mixamorig:lefthandpinky3",
    # Fingers - Right Hand
    "rightthumb1": "mixamorig:righthandthumb1",
    "rightthumbmedial": "mixamorig:righthandthumb1",
    "rightthumb2": "mixamorig:righthandthumb2",
    "rightthumbdistal": "mixamorig:righthandthumb2",
    "rightthumb3": "mixamorig:righthandthumb3",
    "r_thumb1": "mixamorig:righthandthumb1",
    "r_thumb2": "mixamorig:righthandthumb2",
    "r_thumb3": "mixamorig:righthandthumb3",
    "rightindex1": "mixamorig:righthandindex1",
    "rightindexmedial": "mixamorig:righthandindex1",
    "rightindex2": "mixamorig:righthandindex2",
    "rightindexdistal": "mixamorig:righthandindex2",
    "rightindex3": "mixamorig:righthandindex3",
    "r_index1": "mixamorig:righthandindex1",
    "r_index2": "mixamorig:righthandindex2",
    "r_index3": "mixamorig:righthandindex3",
    "rightmiddle1": "mixamorig:righthandmiddle1",
    "rightmiddle2": "mixamorig:righthandmiddle2",
    "rightmiddle3": "mixamorig:righthandmiddle3",
    "r_middle1": "mixamorig:righthandmiddle1",
    "r_middle2": "mixamorig:righthandmiddle2",
    "r_middle3": "mixamorig:righthandmiddle3",
    "rightring1": "mixamorig:righthandring1",
    "rightringmedial": "mixamorig:righthandring1",
    "rightring2": "mixamorig:righthandring2",
    "rightringdistal": "mixamorig:righthandring2",
    "rightring3": "mixamorig:righthandring3",
    "r_ring1": "mixamorig:righthandring1",
    "r_ring2": "mixamorig:righthandring2",
    "r_ring3": "mixamorig:righthandring3",
    "rightpinky1": "mixamorig:righthandpinky1",
    "rightlittlemedial": "mixamorig:righthandpinky1",
    "rightpinky2": "mixamorig:righthandpinky2",
    "rightlittledistal": "mixamorig:righthandpinky2",
    "rightpinky3": "mixamorig:righthandpinky3",
    "r_pinky1": "mixamorig:righthandpinky1",
    "r_pinky2": "mixamorig:righthandpinky2",
    "r_pinky3": "mixamorig:righthandpinky3",
    # Feet/Toes
    "l_foot": "mixamorig:lefttoebase",
    "r_foot": "mixamorig:righttoebase",
    # SMPL-H Uppercase leg/foot variants (CRITICAL for proper matching)
    "L_Hip": "mixamorig:leftupleg",
    "R_Hip": "mixamorig:rightupleg",
    "L_Knee": "mixamorig:leftleg",
    "R_Knee": "mixamorig:rightleg",
    "L_Ankle": "mixamorig:leftfoot",
    "R_Ankle": "mixamorig:rightfoot",
    "L_Foot": "mixamorig:lefttoebase",
    "R_Foot": "mixamorig:righttoebase",
    "bone_0": "mixamorig:hips",  # Unirig Hip
    "bone_8": "mixamorig:leftforearm",  # Unirig L_Elbow
    "bone_26": "mixamorig:rightarm",  # Unirig R_Shoulder
    "bone_27": "mixamorig:rightforearm",  # Unirig R_Elbow
}

# ArticulationXL (UniRig) Bone Mapping (Strictly from unirig.json)
ARTICULATION_MAPPING = {
    "Pelvis": ["bone_0"],
    "L_Hip": ["bone_44"],
    "L_Knee": ["bone_45"],
    "L_Ankle": ["bone_46"],
    "L_Foot": ["bone_47"],
    "R_Hip": ["bone_48"],
    "R_Knee": ["bone_49"],
    "R_Ankle": ["bone_50"],
    "R_Foot": ["bone_51"],
    "Spine1": ["bone_1"],
    "Spine2": ["bone_2"],
    "Spine3": ["bone_3"],
    "Neck": ["bone_4"],
    "Head": ["bone_5"],
    "L_Collar": ["bone_6"],
    "L_Shoulder": ["bone_7"],
    "L_Elbow": ["bone_8"],
    "L_Wrist": ["bone_9"],
    "R_Collar": ["bone_25"],
    "R_Shoulder": ["bone_26"],
    "R_Elbow": ["bone_27"],
    "R_Wrist": ["bone_28"],
    "L_Index1": ["bone_13"],
    "L_Index2": ["bone_14"],
    "L_Index3": ["bone_15"],
    "L_Middle1": ["bone_16"],
    "L_Middle2": ["bone_17"],
    "L_Middle3": ["bone_18"],
    "L_Ring1": ["bone_19"],
    "L_Ring2": ["bone_20"],
    "L_Ring3": ["bone_21"],
    "L_Pinky1": ["bone_22"],
    "L_Pinky2": ["bone_23"],
    "L_Pinky3": ["bone_24"],
    "L_Thumb1": ["bone_10"],
    "L_Thumb2": ["bone_11"],
    "L_Thumb3": ["bone_12"],
    "R_Index1": ["bone_32"],
    "R_Index2": ["bone_33"],
    "R_Index3": ["bone_34"],
    "R_Middle1": ["bone_35"],
    "R_Middle2": ["bone_36"],
    "R_Middle3": ["bone_37"],
    "R_Ring1": ["bone_38"],
    "R_Ring2": ["bone_39"],
    "R_Ring3": ["bone_40"],
    "R_Pinky1": ["bone_41"],
    "R_Pinky2": ["bone_42"],
    "R_Pinky3": ["bone_43"],
    "R_Thumb1": ["bone_29"],
    "R_Thumb2": ["bone_30"],
    "R_Thumb3": ["bone_31"],
}

# UE5 Bone Mapping (Strictly from user request)
UE5_MAPPING = {
    "Pelvis": ["pelvis"],
    "Spine1": ["spine_01", "spine_02"],
    "Spine2": ["spine_03"],
    "Spine3": ["spine_04", "spine_05"],
    "Neck": ["neck_01", "neck_02", "neck_03"],
    "Head": ["head"],
    "L_Collar": ["clavicle_l"],
    "R_Collar": ["clavicle_r"],
    "L_Shoulder": ["upperarm_l"],
    "R_Shoulder": ["upperarm_r"],
    "L_Elbow": ["lowerarm_l"],
    "R_Elbow": ["lowerarm_r"],
    "L_Wrist": ["hand_l"],
    "R_Wrist": ["hand_r"],
    "L_Hip": ["thigh_l"],
    "L_Knee": ["calf_l"],
    "L_Ankle": ["foot_l"],
    "R_Hip": ["thigh_r"],
    "R_Knee": ["calf_r"],
    "R_Ankle": ["foot_r"],
    "L_Foot": ["ball_l"],
    "R_Foot": ["ball_r"],
    "L_Thumb1": ["thumb_01_l"],
    "L_Thumb2": ["thumb_02_l"],
    "L_Thumb3": ["thumb_03_l"],
    "L_Index1": ["index_01_l"],
    "L_Index2": ["index_02_l"],
    "L_Index3": ["index_03_l"],
    "L_Middle1": ["middle_01_l"],
    "L_Middle2": ["middle_02_l"],
    "L_Middle3": ["middle_03_l"],
    "L_Ring1": ["ring_01_l"],
    "L_Ring2": ["ring_02_l"],
    "L_Ring3": ["ring_03_l"],
    "L_Pinky1": ["pinky_01_l"],
    "L_Pinky2": ["pinky_02_l"],
    "L_Pinky3": ["pinky_03_l"],
    "R_Thumb1": ["thumb_01_r"],
    "R_Thumb2": ["thumb_02_r"],
    "R_Thumb3": ["thumb_03_r"],
    "R_Index1": ["index_01_r"],
    "R_Index2": ["index_02_r"],
    "R_Index3": ["index_03_r"],
    "R_Middle1": ["middle_01_r"],
    "R_Middle2": ["middle_02_r"],
    "R_Middle3": ["middle_03_r"],
    "R_Ring1": ["ring_01_r"],
    "R_Ring2": ["ring_02_r"],
    "R_Ring3": ["ring_03_r"],
    "R_Pinky1": ["pinky_01_r"],
    "R_Pinky2": ["pinky_02_r"],
    "R_Pinky3": ["pinky_03_r"],
}

# Daz Genesis 9 (G9) Bone Mapping
G9_MAPPING = {
    "Pelvis": ["hip"],
    "Spine1": ["pelvis", "spine1"],
    "Spine2": ["spine2", "spine3"],
    "Spine3": ["spine4"],
    "Neck": ["neck1", "neck2"],
    "Head": ["head"],
    "L_Collar": ["l_shoulder"],
    "R_Collar": ["r_shoulder"],
    "L_Shoulder": ["l_upperarm"],
    "R_Shoulder": ["r_upperarm"],
    "L_Elbow": ["l_forearm"],
    "R_Elbow": ["r_forearm"],
    "L_Wrist": ["l_hand"],
    "R_Wrist": ["r_hand"],
    "L_Hip": ["l_thigh"],
    "L_Knee": ["l_shin"],
    "L_Ankle": ["l_foot"],
    "R_Hip": ["r_thigh"],
    "R_Knee": ["r_shin"],
    "R_Ankle": ["r_foot"],
    "L_Foot": ["l_toes"],
    "R_Foot": ["r_toes"],
    # Fingers - Left
    "L_Thumb1": ["l_thumb1"],
    "L_Thumb2": ["l_thumb2"],
    "L_Thumb3": ["l_thumb3"],
    "L_Index1": ["l_index1"],
    "L_Index2": ["l_index2"],
    "L_Index3": ["l_index3"],
    "L_Middle1": ["l_mid1"],
    "L_Middle2": ["l_mid2"],
    "L_Middle3": ["l_mid3"],
    "L_Ring1": ["l_ring1"],
    "L_Ring2": ["l_ring2"],
    "L_Ring3": ["l_ring3"],
    "L_Pinky1": ["l_pinky1"],
    "L_Pinky2": ["l_pinky2"],
    "L_Pinky3": ["l_pinky3"],
    # Fingers - Right
    "R_Thumb1": ["r_thumb1"],
    "R_Thumb2": ["r_thumb2"],
    "R_Thumb3": ["r_thumb3"],
    "R_Index1": ["r_index1"],
    "R_Index2": ["r_index2"],
    "R_Index3": ["r_index3"],
    "R_Middle1": ["r_mid1"],
    "R_Middle2": ["r_mid2"],
    "R_Middle3": ["r_mid3"],
    "R_Ring1": ["r_ring1"],
    "R_Ring2": ["r_ring2"],
    "R_Ring3": ["r_ring3"],
    "R_Pinky1": ["r_pinky1"],
    "R_Pinky2": ["r_pinky2"],
    "R_Pinky3": ["r_pinky3"],
}

# Daz Genesis 3 (G3) Bone Mapping
G3_MAPPING = {
    "Pelvis": ["hip"],
    "Spine1": ["pelvis", "abdomenLower", "abdomenUpper"],
    "Spine2": ["chestLower"],
    "Spine3": ["chestUpper"],
    "Neck": ["neckLower", "neckUpper"],
    "Head": ["head"],
    # Legs (Vector alignment + Twist support)
    "L_Hip": ["lThighBend"],
    "L_Knee": ["lShin"],
    "L_Ankle": ["lFoot"],
    "L_Foot": ["lToe"],
    "R_Hip": ["rThighBend"],
    "R_Knee": ["rShin"],
    "R_Ankle": ["rFoot"],
    "R_Foot": ["rToe"],
    # Arms (Vector alignment + Twist support)
    "L_Collar": ["lCollar"],
    "L_Shoulder": ["lShldrBend"],
    "L_Elbow": ["lForearmBend"],
    "L_Wrist": ["lHand"],
    "R_Collar": ["rCollar"],
    "R_Shoulder": ["rShldrBend"],
    "R_Elbow": ["rForearmBend"],
    "R_Wrist": ["rHand"],
    # Fingers - Left
    "L_Thumb1": ["lThumb1"],
    "L_Thumb2": ["lThumb2"],
    "L_Thumb3": ["lThumb3"],
    "L_Index1": ["lIndex1"],
    "L_Index2": ["lIndex2"],
    "L_Index3": ["lIndex3"],
    "L_Middle1": ["lMid1"],
    "L_Middle2": ["lMid2"],
    "L_Middle3": ["lMid3"],
    "L_Ring1": ["lRing1"],
    "L_Ring2": ["lRing2"],
    "L_Ring3": ["lRing3"],
    "L_Pinky1": ["lPinky1"],
    "L_Pinky2": ["lPinky2"],
    "L_Pinky3": ["lPinky3"],
    # Fingers - Right
    "R_Thumb1": ["rThumb1"],
    "R_Thumb2": ["rThumb2"],
    "R_Thumb3": ["rThumb3"],
    "R_Index1": ["rIndex1"],
    "R_Index2": ["rIndex2"],
    "R_Index3": ["rIndex3"],
    "R_Middle1": ["rMid1"],
    "R_Middle2": ["rMid2"],
    "R_Middle3": ["rMid3"],
    "R_Ring1": ["rRing1"],
    "R_Ring2": ["rRing2"],
    "R_Ring3": ["rRing3"],
    "R_Pinky1": ["rPinky1"],
    "R_Pinky2": ["rPinky2"],
    "R_Pinky3": ["rPinky3"],
}

# Add fuzzy aliases FOR THE SOURCE only - prevents mapping to incorrect target bones like thigh_twist
UE5_SOURCE_ALIASES = {
    "Spine2": ["Spine2", "Chest"],
    "Spine3": ["Spine3", "Chest"],
    "L_Knee": ["L_Knee", "LowerLeg_L"],
    "R_Knee": ["R_Knee", "LowerLeg_R"],
    "L_Ankle": ["L_Ankle", "L_Foot", "Ankle_L"],
    "R_Ankle": ["R_Ankle", "R_Foot", "Ankle_R"],
    "L_Foot": ["L_Toe", "Ball_L"],
    "R_Foot": ["R_Toe", "Ball_R"],
}

# Comprehensive bone name aliases for fuzzy matching
FUZZY_ALIASES = {
    "hips": [
        "pelvis",
        "root_joint",
        "spine_01",
        "hip",
        "root",
        "cog",
        "center",
        "base",
    ],
    "spine": ["spine", "chest", "back", "torso", "spine1", "spine2", "spine3"],
    "neck": [
        "neck",
        "neck_01",
        "neckbase",
        "neck1",
        "neck2",
        "cervical",
        "c1",
        "c2",
        "c3",
        "c4",
        "c5",
        "c6",
        "c7",
    ],
    "head": ["head", "head_top", "skull", "cranium", "head1", "head2"],
    "upleg": ["thigh", "hip", "upperleg", "leg_upper", "femur"],
    "leg": ["knee", "leg", "lowerleg", "leg_lower", "shin", "calf"],
    "foot": ["ankle", "foot", "ankle_01"],
    "toe": ["toe", "ball", "toebase", "foot_end"],
    "shoulder": ["collar", "clavicle", "shoulder_01", "scapula"],
    "arm": ["shoulder", "upperarm", "arm", "arm_upper", "humerus"],
    "forearm": ["elbow", "forearm", "arm_lower", "lowerarm", "ulna"],
    "hand": ["wrist", "hand", "palm"],
    "thumb": ["thumb", "pollex"],
    "index": ["index", "pointer"],
    "middle": ["middle", "long"],
    "ring": ["ring", "third"],
    "pinky": ["pinky", "little", "small"],
}

BONE_KEYWORDS = {
    "root": ["hips", "pelvis", "root", "cog", "center"],
    "spine": ["spine", "chest", "back", "torso"],
    "neck": ["neck"],
    "head": ["head", "skull"],
    "leg": ["upleg", "thigh", "knee", "leg", "ankle", "foot", "toe"],
    "arm": [
        "shoulder",
        "collar",
        "clavicle",
        "arm",
        "elbow",
        "forearm",
        "hand",
        "wrist",
    ],
    "finger": ["thumb", "index", "middle", "ring", "pinky", "digit"],
}
